

[pack]
name = "Routines for Jarvis"
description = "Jarvis Chatbot routines"
version = "0.1.0"
author = "Sam Partee"
email = "sam@partee.io"

[modules]
gmail = "0.0.1"
read_sqlite = "0.0.1"
BM25 = "0.0.1"
people = "0.1.0"
